### PR TITLE
Incorporate JOSS changes

### PR DESCRIPTION
**Pull request by jfowkes**
Our JOSS paper re-review has more suggestions for improvement:
https://github.com/openjournals/joss-reviews/issues/4377

Broadly these come down to:
- [x] add CONTRIBUTING.md
- [x] clarify conventions for contributing
- [x] change order of authors in the paper (move Arpad to last author)
- [x] make `sifdecode_extras.py ` use human-readable problem properties
- [x] change how to interpret the problem properties when n=None or m=None
- [x] improve Docker installation
- [x] version bump and update release history
- [x] rebuild and verify documentation

@lindonroberts your thoughts on these? I think good suggestions.

### CODE REVIEW

**Comment by lindonroberts** [comment]
@jfowkes - I agree, this all looks good. Specifically, my thoughts are:

- CONTRIBUTING.md. It looks like [Mozilla](https://mozillascience.github.io/working-open-workshop/contributing/) and [Github](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors) have some suggestions for how to write this. 
- Conventions for contributing: we can answer this in contributing.md, but I would suggest we keep it simple with either pull requests for code changes or github issues for everything else (reporting features, bugs, etc.).
- Authors: this is fine
- The classification scheme URL is given in the docstring for `problem_properties` in `sifdecode_extras.py`, which then feeds through to the [documentation](https://jfowkes.github.io/pycutest/_build/html/functions/pycutest.problem_properties.html). We could also potentially update that function to have more human-readable info perhaps? e.g. replace CUTEr classification code with an actual description, like `'constraints': 'unconstrained'` rather than `'constraints': 'U'`. I agree we should add a link in the paper and documentation (the "finding problems" section of "building test problems") however.
- We could replace `'n': None` with `'n': 'variable'`? This means it no longer always returns an `int`, but the same holds with returning None as currently. This would fit with human-readable problem properties.
- Docker: we can try to make it easy on our side, but I don't know that there's much we can do for the basic CUTEst installation. Is there a way to use [Dominique's installation package](https://github.com/optimizers/homebrew-cutest)?

**Comment by lindonroberts** [comment]
Also this comment: "Generally, I think the [Install](https://jfowkes.github.io/pycutest/_build/html/install.html) docs could be tightened up to make it easier to digest. e.g., why waste space on "Manual installation of PyCUTEst", PYTEST_CACHE, NumPy or SciPy? Most of those elements are automatically handled or can be delegated to a "Development install" section."

We can make a development install section and simplify what we do have, but we need the CUTEst instructions and how to set the cache variable (on linux).

**Comment by jfowkes** [comment]
@lindonroberts I agree with most of your thinking, in addition I would say:

- CONTRIBUTING.md and contributing conventions: agreed
- While I would prefer to have the classification scheme be more human-readable, I worry that this would be a breaking change to the querying functions as e.g. we would have to replace `find_problems(objective='Q')` with `find_problems(objective='quadratic')` unless we retain both for backward compatibility? Not sure how much work that would involve...
- I like the idea of replacing 'n': None with 'n': 'variable', this is much clearer
- I will investigate how Dominique's CUTEst installation package works, it might be relatively easy to adapt it for Linux and then we can ship our own with pycutest
- I agree with having a development install section for the advanced installation stuff, might also be a natural place for the docker install? I'm not a docker user.

Also I noticed today that the error message when using hess (or sphess) and not passing in a Lagrange multiplier vector v for a constrained problem is not very friendly:
```python
Traceback (most recent call last):
  File "/Users/jari/s_matrix.py", line 20, in <module>
    H = prob.sphess(x0)  # Sparse Hessian (COO)
  File "/usr/local/lib/python3.9/site-packages/pycutest/problem_class.py", line 667, in sphess
    self.check_input_v(v)
  File "/usr/local/lib/python3.9/site-packages/pycutest/problem_class.py", line 225, in check_input_v
    elif v.shape != (self.m,):
AttributeError: 'NoneType' object has no attribute 'shape'
```
We should probably make this a little more informative (had me stumped for a while)?

As for next steps, we should probably divide up the work between us somehow, do you have a preference for which things you'd like to tackle?

In other news: I'm now proficient with the Python and NumPy C APIs so will probably have a go at re-writing relevant bits of `c_interface.py` later this year to modernise it and remove some of the major pain points (like returning arrays for single values, no need for this).

**Comment by lindonroberts** [comment]
@jfowkes - I have made some changes today:

- Added a first draft of CONTRIBUTING.md. I haven't updated the documentation
- Updated the problem properties to be `'n': 'variable'` and `'m': 'variable'` for variable-dimension problems. Updated unit tests and `find_problems()` based on this new convention. I have not rebuilt the documentation with this, but the docstring has been updated, so the documentation rebuild will have the new information, I hope.
- Updated author order for the paper (and updated my affiliation)

Things I haven't looked at in the latest commits:

- Links to classification scheme in documentation/readme
- Docker installation
- The `hess` and `sphess` issue you mentioned above. I agree this probably needs fixing (but maybe not in this pull request since it's unrelated to the JOSS submission?)

**Comment by lindonroberts** [comment]
Opened issue #27 for the `hess`/`sphess` issue you mentioned above

**Comment by jfowkes** [comment]
@lindonroberts many thanks for this! I'm happy to have a go at the things you haven't looked at later on today. I will also fix the failing macOS CI tests that now seem to be failing for some reason (unrelated to your changes).

**Comment by jfowkes** [comment]
@lindonroberts I'm back from holiday now, will pick this back up asap.

**Comment by jfowkes** [comment]
@lindonroberts I have made the following additional changes:

- `problem_properties` and `find_problems()` now use human-readable descriptions as discussed
- the Linux CUTEst installation has been simplified to a one-liner without human input (as in the CI)
- similarly for the Dockerfile (no human input is required, has been tested)

Could you review the above changes? Happy to take suggestions for improvement.

Once that's done I think we should do a new release as the human-readable descriptions are a (minor) breaking change and ask JOSS to re-review it.

**Review by lindonroberts — APPROVED** [review]
Thanks @jfowkes - I'm happy with all these changes. Since we updated the problem properties interface in a breaking way, we should minimise the time between updating master with the new changes and releasing a new version on pypi (so that the online documentation is not out-of-date). That will also require an update to docs/history.rst.

**Comment by jfowkes** [comment]
@lindonroberts agreed I'll do the version bump and related updates in this pull request. Then it should be a simple two-step process of merging this to master and creating a new release on github which should trigger an automatic pypi update.

**Comment by lindonroberts** [comment]
Thanks @jfowkes!

**Pull request merged**
