### PR TITLE
Update docs and CI tests

### PR DESCRIPTION
**Pull request by jfowkes**
Update documentation and CI tests in response to issues raised in JOSS paper review:
https://github.com/openjournals/joss-reviews/issues/4377

In particular:
- [x] Add guidelines for third-party contributors
- [x] State the problem of interest more clearly
- [x] Add types to problem method docstrings
- [x] Remove testing section from docs
- [x] Add dockerfile as alternate install option
- [x] Add scheduled CI tests
- [x] Remove ancient tests from the examples directory 

Then rebuild the docs using Sphinx.

### CODE REVIEW

**Comment by jfowkes** [comment]
@lindonroberts would you be able to review this?

**Comment by lindonroberts** [comment]
Thanks Jari, this all looks really good! Just a couple of very small suggestions:

- In the "Installing CUTEst on Mac" documentation, change comma to full stop in "when using PyCUTEst on Mac, to suppress"
- For the docker file, do you have to save it as "cutest" or something like that for the bash commands to work?

Otherwise, I'm happy with everything you have added, thanks for doing this!

**Comment by jfowkes** [comment]
Many thanks Lindon! I will fix the comma as per your suggestion. For the dockerfile, it should be called "Dockerfile" for the commands to work, I will add this to the docs (the docker image gets called "cutest" by virtue of the "-t" tag passed to docker build).

**Comment by lindonroberts** [comment]
Thanks Jari! Is there anything more needed for the JOSS review?

**Comment by diehlpk** [comment]
@stsievert, @jonjoncardoso could you please have a look?

**Pull request merged**
