### PR TITLE
Remove deprecated calls

### PR DESCRIPTION
**Pull request by ragonneau**
Hi @jfowkes,

Here are the modifications we discussed. They include

1. removing the deprecated calls to `np.int` and `np.bool`,
2. removing importations of unused libraries,
3. replacing the call to the deprecated `python setup.py install` by `python setup.py build_ext --inplace`, and
4. using `setuptools` instead of `distutils` to compile the external sources.

Note that the original call `python setup.py install` was slightly unnecessary, as only the external libraries was used by `pycutest`. Also, I created a configuration file for using [tox](https://tox.wiki/en/latest/) to test the software. Assuming that you have installed on your machine `python3.6`, `python3.7`, `python3.8`, `python3.9`, and `python3.10`, and that CUTEst is correctly set up, you can test `pycutest` against all versions of Python by install `tox` via PyPI and running `python -m tox`.

I hope this time things will work on macOS.
Tom.

### CODE REVIEW

**Comment by jfowkes** [comment]
Hi @ragonneau,

Many thanks, this looks really good! I don't have access to my mac today but I will test it out on Monday. I see no reason in principle why this shouldn't work on macOS.

Regards,
Jari

**Comment by jfowkes** [comment]
I've just added macOS tests to our GitHub Actions CI. @ragonneau could you rebase / merge master into this PR? The macOS tests should then run automatically!

**Comment by jfowkes** [comment]
@ragonneau I've now merged this to master, many thanks for your contribution! We'll do a new release shortly once I address #10 on Mac which is annoying me.

**Comment by lindonroberts** [comment]
Thanks @ragonneau and @jfowkes - this all looks great!

**Pull request merged**
